image: alpine

before_script:
  - apk update
  - apk upgrade
  - apk add cmake make clang g++

.script: &script
  script:
    - ctest -V -C Release -S cmake/TestVecCore.cmake

stages:
  - build

g++:
  stage: build
  <<: *script
  variables:
    CC: gcc
    CXX: g++

clang:
  stage: build
  <<: *script
  variables:
    CC: clang
    CXX: clang++
